# Generated by Django 4.0.4 on 2022-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4000)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Post access token',
                'verbose_name_plural': 'Post access tokens',
            },
        ),
    ]
